### ISSUE TITLE
How to remember last menu state after a click or a page reload

### ISSUE THREAD

**Issue by et7223** [tangpanqing/eosMenu#1]
First, I would like to say that I love your menu.
Second, there are 3 things that I think would make your menu work even better:

 1) remember the last state of menu being expand.
 2) allow to load page(http) on click of Main group title menu
     Company          <--- allow this to load a page of Company when click
           Facility
           Contact Us

 3) allow option to default always expand selected Group Menu.

But my priority request is if you can show me how I can have the menu Remember the last state (option #1) would be greatly appreciated.

**Comment by tangpanqing** [comment]
thanks for use, my friend.
for your suggestion,

1, is ok,  pay attention the default properties:  isAutoUrl & defaultUrl

2, the group tilte is just a title for remind, so I think it's no need for url and so on.

3, see the first.

have a nice day.

**Comment by eugenio11** [comment]
Hello,
thanks for having shared your project.
I have a (maybe) similar issue but I don't see how to solve it using isAutoUrl & defaultURL.
Let's say I want to expand a particular group when the page is loaded. First of all I guess I need to add an ID to each group, then which is the cleanest way to expand the group having a specified ID?

Thanks.
